pipeline {

  agent {
    node {
      // slave with Docker
      label 'docker-build-node'
    }
  }

  // using the Timestamper plugin we can add timestamps to the console log
  options {
    timestamps()
  }

  environment {
    DOCKER_REGISTRY = "249767383774.dkr.ecr.ap-southeast-1.amazonaws.com"
    CREDENTIAL_ID = "ecr:ap-southeast-1:jenkins-ecr"
    IMAGE = "proximax-catapult-explorer"
  }

 stages {
    stage('Build') {
      steps {
        echo 'Building'
        // TODO: Build on Docker image
      }
      post {
        success {
          echo 'Build Success'
        }
      }
    }

    stage('Unit Test') {
      steps {
        echo 'Running Unit Tests'
      }
    }

    stage('Build and Publish Release Image') {
      when {
        tag "release-*"   // only run these stage in tag release-*
      }
      steps {
        echo "Build and Publish Image for ${env.GIT_BRANCH}"

        script {
            def newImage = docker.build("${IMAGE}")
            docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                newImage.push("${env.GIT_BRANCH}") // if a tag commit, then env.GIT_BRANCH returns the tag name instead of a branch
            }
        }
      }
      post {
        success {
            slackSend channel: '#devops',
                color: 'good',
                message: "Release with Tag *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker image ${DOCKER_REGISTRY}/${IMAGE}:${env.GIT_BRANCH}"
        }
      }
    }

    stage('Build and Publish Develop Image') {
      when {
        branch 'develop'  // only run this stage in the develop branch
      }
      steps {
        echo 'Build and Publish Image'

        script {
            def newImage = docker.build("${IMAGE}")
            docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                newImage.push("develop-jenkins-build-${env.BUILD_NUMBER}") // also push using Jenkins build number
                newImage.push("develop") // update Docker image develop
            }
        }
      }
      post {
        success {
            slackSend channel: '#devops',
                color: 'good',
                message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:\nPushed Docker images ${DOCKER_REGISTRY}/${IMAGE}:develop-jenkins-build-${env.BUILD_NUMBER} and ${DOCKER_REGISTRY}/${IMAGE}:develop"
        }
      }
    }
  }

  post {
    failure {
        slackSend channel: '#devops',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}
